# Generated by Django 5.1.3 on 2025-01-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
